import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class VehicleMakesModelsService {
  makes = [
    'Acura',
    'Alfa Romeo',
    'Aston Martin',
    'Audi',
    'BMW',
    'Buick',
    'Cadillac',
    'Chevrolet',
    'Chrysler',
    'Daihatsu',
    'Daewoo',
    'Dodge',
    'Fiat',
    'Ford',
    'GMC',
    'Honda',
    'Hyundai',
    'Hummer',
    'Infiniti',
    'Isuzu',
    'Jaguar',
    'Jeep',
    'Kia',
    'Land Rover',
    'Lexus',
    'Lincoln',
    'Maserati',
    'Mazda',
    'Mercedes-Benz',
    'Mini',
    'Mitsubishi',
    'Nissan',
    'Porsche',
    'Saab',
    'Subaru',
    'Suzuki',
    'Tesla',
    'Toyota',
    'Volkswagen',
    'Volvo'
  ];
  makesAndModels = {
    Acura: [
      'CL',
      'ILX',
      'Integra',
      'Legend',
      'MDX',
      'NSX',
      'RDX',
      'RL',
      'RLX',
      'RSX',
      'SLX',
      'TL',
      'TLX',
      'TSX',
      'Vigor',
      'ZDX'
    ],
    'Alfa Romeo': [
      '164',
      '4C',
      '8C Competizione Spider',
      'GTV6',
      'Giulia (952)',
      'Milano',
      'Spider ',
      'Stelvio'
    ],
    'Aston Martin': [
      'DB11',
      'DB9',
      'DBS',
      'Lagonda',
      'Rapide',
      'V12 Vantage',
      'V8 Vantage',
      'Vanquish',
      'Vantiage',
      'Virage'
    ],
    Audi: [
      '100',
      '200',
      '4000',
      '5000',
      '80',
      '90',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'A8',
      'Cabriolet',
      'Coupe',
      'Q3',
      'Q5',
      'Q7',
      'Q8',
      'R8',
      'RS3',
      'RS4',
      'RS5',
      'RS6',
      'RS7',
      'S3',
      'S4',
      'S5',
      'S6',
      'S7',
      'S8',
      'SQ5',
      'TT',
      'TT RS',
      'TTS',
      'V8',
      'Allroad'
    ],
    BMW: [
      '100 Series',
      '200 Series',
      '300 Series',
      '400 Series',
      '500 Series',
      '600 Series',
      '700 Series',
      '800 Series',
      '900 Series',
      'M Series',
      'X Series'
    ],
    Buick: [
      'Allure',
      'Cascada',
      'Century',
      'Coachbuilder',
      'Electra',
      'Enclave',
      'Encore',
      'Envision',
      'Estate',
      'Incomplete',
      'LaCrosse',
      'LeSabre',
      'Lucerne',
      'Opel Sintra',
      'Park Avenue',
      'Rainier',
      'Reatta',
      'Regal',
      'Regal TourX',
      'Rendezvous',
      'Riviera',
      'Roadmaster',
      'Skyhawk',
      'Skylark',
      'Somerset',
      'Terraza',
      'Verano'
    ],
    Cadillac: [
      '60 Special',
      'ATS',
      'Allante',
      'Brougham',
      'CT6',
      'CTS',
      'Catera',
      'Cimarron',
      'DTS',
      'Deville',
      'ELR',
      'Eldorado',
      'Escalade',
      'Fleetwood',
      'Funeral Coach',
      'Hearse ',
      'Limousine',
      'SLS',
      'SRX',
      'STS',
      'Seville',
      'Stretched Limousine',
      'XLR',
      'XT4',
      'XT5',
      'XTS'
    ],
    Chevrolet: [
      '3 ton',
      '3500 / 3500HD / 4500',
      'Alero',
      'Astro Van',
      'Avalanche',
      'Aveo',
      'Beretta',
      'Blazer',
      'Bolt EV',
      'C/K Pickup',
      'Camaro',
      'Caprice',
      'Caprice',
      'Captiva Sport',
      'Cavalier',
      'Chevette',
      'Cobalt',
      'Colorado',
      'Corsica',
      'Corvette',
      'Cruze',
      'El Camino',
      'Epica',
      'Equinox',
      'Express',
      'Hearse/Limo',
      'Impala',
      'Lumina',
      'Lumina APV',
      'Magnus',
      'Malibu',
      'Monte Carlo',
      'Nova',
      'Orlando',
      'P Series',
      'Rezzo',
      'S-10 Pickup',
      'S6',
      'SS',
      'SSR',
      'Silverado',
      'Sonic',
      'Spark',
      'Suburban',
      'T-Series',
      'Tahoe',
      'Tracker',
      'Trailblazer',
      'Traverse',
      'Trax',
      'Uplander',
      'Venture',
      'Volt'
    ],
    Chrysler: [
      '200',
      '300',
      'Aspen',
      'Avenger',
      'Caravan',
      'Cirrus',
      'Concorde',
      'Conquest',
      'Cordoba',
      'Crossfire',
      'Daytona',
      'Dynasty',
      'E-Class',
      'Executive',
      'Fifth Avenue',
      'Grand Voyager',
      'Hybrid Electric',
      'Imperial',
      'Intrepid',
      'LeBaron',
      'Neon',
      'Newport',
      'New Yorker',
      'Orion II',
      'Orion V',
      'Orion VI',
      'Orion VII',
      'PT Cruiser',
      'Pacifica',
      'Prowler',
      'Salon',
      'Sebring',
      'Shadow',
      'Spirit',
      'Stratus',
      'TC',
      'Town & Country',
      'Viper',
      'Vision',
      'Voyager'
    ],
    Daihatsu: ['Charade', 'Daihatsu', 'Rocky'],
    Daewoo: ['Lanos', 'Leganza', 'Leganza VCar', 'Nubira', 'Roadster/G2X'],
    Dodge: [
      '400',
      '480 Series',
      '580 Series',
      '600',
      'Aries',
      'Avenger',
      'Caliber',
      'Caravan',
      'Challenger',
      'Charger',
      'Colt',
      'Conquest',
      'D-Series',
      'Dakota',
      'Dart',
      'Daytona',
      'Diplomat',
      'Durango',
      'Dynasty',
      'Grand Caravan',
      'Intrepid',
      'Journey',
      'Lancer',
      'Magnum',
      'Mirada',
      'Monaco',
      'Neon',
      'Nitro',
      'Omni',
      'Raider',
      'Ram',
      'Ram Van',
      'Ram Wagon',
      'Ramcharger',
      'Rampage',
      'Royal Mini Ram Van',
      'Shadow',
      'Shelby',
      'Spirit',
      'Sprinter',
      'St.Regis',
      'Stealth',
      'Stratus',
      'Viper',
      'W-Series'
    ],
    Fiat: [
      '124 Spider',
      '500',
      '500L',
      '500X',
      'Brava',
      'Ducato',
      'Freemont',
      'Spider 2000',
      'Strada',
      'X 1/9'
    ],
    Ford: [
      'Aerostar',
      'Aspire',
      'Bronco',
      'C-max',
      'Contour',
      'Cordova Sedan',
      'Courier',
      'Crown Victoria',
      'Ecosport',
      'Edge',
      'Escape',
      'Escort',
      'Excursion',
      'Expedition',
      'Expedition MAX',
      'Explorer',
      'Explorer Sport',
      'Explorer Sport Trac',
      'F150',
      'F250',
      'F350',
      'F450',
      'F550',
      'F650',
      'F750',
      'F800',
      'F Super Duty',
      'Fairmont',
      'Festiva',
      'Fiesta',
      'Five Hundred',
      'Flex',
      'Focus',
      'Freestar',
      'Freestyle',
      'Fusion',
      'GT',
      'Granada',
      'Laser',
      'Malibu Sedan',
      'Mustang',
      'Pinto',
      'Probe',
      'Ranger',
      'Super Duty',
      'Taurus',
      'Tempo',
      'Thunderbird',
      'Transit',
      'Windstar',
      'ZX2'
    ],
    GMC: [
      '3 ton',
      'Acadia',
      'C-Series',
      'Caballero',
      'Canyon',
      'Cyclone',
      'Envoy',
      'Hi-Cube',
      'Jimmy',
      'Rally',
      'S15 Pickup',
      'Safari',
      'Savana',
      'Sierra',
      'Sonoma',
      'Suburban',
      'T-Series',
      'Terrain',
      'Typhoon',
      'V Conventional',
      'Vandura',
      'Yukon',
      'Yukon XL'
    ],
    Honda: [
      'Accord',
      'CR-V',
      'CR-Z',
      'Civic',
      'Element',
      'FCX Clarity',
      'Fit',
      'GL',
      'Insight',
      'Odyssey',
      'Pilot',
      'Ridgeline',
      'VT'
    ],
    Hyundai: [
      'Accent',
      'Azera',
      'Elantra',
      'Entourage',
      'Equus',
      'Excel',
      'Genesis',
      'Genesis Coupe',
      'Ioniq Electric',
      'Ioniq Hybrid',
      'Kona',
      'Nexo',
      'Pony',
      'Santa Fe',
      'Scoupe',
      'Sonata',
      'Stellar',
      'Tiburon',
      'Tucson',
      'Veloster',
      'Veracruz',
      'XG 350',
      'XG 300'
    ],
    Hummer: ['H1', 'H2', 'H3'],
    Infiniti: [
      'EX35',
      'FX35',
      'FX37',
      'FX45',
      'FX50',
      'G20',
      'G25',
      'G35',
      'G37',
      'I30',
      'I35',
      'J30',
      'JX35',
      'M30',
      'M35',
      'M35h',
      'M37',
      'M45',
      'M56',
      'Q40',
      'Q45',
      'Q50',
      'Q60',
      'Q70',
      'Q70L',
      'QX30',
      'QX4',
      'QX50',
      'QX56',
      'QX60',
      'QX70',
      'QX80'
    ],
    Isuzu: [
      '4000 Series Medium Duty',
      '6000 Series Medium Duty',
      '7000 Series Medium Duty',
      '8000 Series Medium Duty',
      'Amigo',
      'Ascender',
      'Axiom',
      'F6',
      'F7',
      'FSR',
      'FTR/FVR',
      'H-Series',
      'Hombre',
      'I-Mark',
      'Oasis',
      'Passport',
      'Pickup',
      'Rodeo',
      'Stylus ',
      'Trooper',
      'VehiCross'
    ],
    Jaguar: [
      'E PACE',
      'F Pace',
      'F Type',
      'I PACE',
      'S Type',
      'Sovereign',
      'VDP',
      'X Type',
      'X100',
      'XE',
      'XF',
      'XJ',
      'XJ Sedan',
      'XJ6',
      'XJ8/XJ8L',
      'XJR',
      'XJS',
      'XK',
      'XK8'
    ],
    Jeep: [
      'CJ-5',
      'CJ-6',
      'CJ-7',
      'CJ-8 Scrambler',
      'Cherokee',
      'Comanche',
      'Commander',
      'Compass',
      'Grand Cherokee',
      'Grand Wagoneer',
      'J-10',
      'J-20',
      'Liberty',
      'Liberty Cherokee',
      'Patriot',
      'Renegade',
      'Wagoneer',
      'Wrangler',
      'Wrangler JK'
    ],
    Kia: [
      'Amanti',
      'Borrego',
      'Cadenza',
      'Forte',
      'Forte Koup',
      'K900',
      'Niro',
      'Optima',
      'Rio',
      'Rondo',
      'Sedona',
      'Sephia',
      'Sorento',
      'Soul',
      'Soul EV',
      'Spectra',
      'Sportage',
      'Stinger'
    ],
    'Land Rover': [
      'Defender',
      'Discovery',
      'Discovery Sport',
      'Freelander',
      'LR2',
      'LR3',
      'LR4',
      'Range Rover'
    ],
    Lexus: [
      'CT',
      'ES',
      'GS',
      'GX',
      'HS',
      'IS',
      'LC',
      'LFA',
      'LS',
      'LX',
      'LX 570',
      'NX',
      'RC',
      'RC F',
      'RX',
      'SC',
      'UX'
    ],
    Lincoln: [
      'Aviator',
      'Blackwood',
      'Continental',
      'LS',
      'MKC',
      'MKS',
      'MKT',
      'MKX',
      'MKZ',
      'Mark',
      'Nautilus',
      'Navigator',
      'Town Car',
      'Zephyr'
    ],
    Maserati: [
      '228',
      '430',
      'Biturbo',
      'Coupe',
      'Ghibli',
      'Granturismo',
      'Levante',
      'Merak',
      'Quattroporte',
      'Spyder',
      'TC'
    ],
    Mazda: [
      '323',
      '626',
      '929',
      'B Series',
      'CX-3',
      'CX-5',
      'CX-7',
      'CX-9',
      'GLC',
      'MPV',
      'MX-3',
      'MX-5',
      'MX-6',
      'Mazda2',
      'Mazda3',
      'Mazda5',
      'Mazda6',
      'Millenia',
      'Navajo',
      'Protege',
      'RX-7',
      'RX-8',
      'Tribute'
    ],
    'Mercedes-Benz': [
      '190',
      '240',
      '260',
      '280',
      '300',
      '350',
      '380',
      '400',
      '420',
      '500',
      '560',
      '600',
      'A Class',
      'AMG GT',
      'B Class',
      'C Class',
      'CL Class',
      'CLA Class',
      'CLK Class',
      'CLS Class',
      'E Class',
      'G Class',
      'GL Class',
      'GLA Class',
      'GLC',
      'GLE',
      'GLK Class',
      'GLS Class',
      'M Class',
      'ML Class',
      'R Class',
      'S Class',
      'SL Class',
      'SLC Class',
      'SLK Class',
      'Sprinter'
    ],
    Mini: [
      'Cooper',
      'Cooper Clubman',
      'Cooper Convertible',
      'Cooper Countryman',
      'Cooper Coupe',
      'Cooper Hardtop',
      'Cooper Paceman',
      'Cooper Roadster',
      'Cooper S',
      'Cooper S Clubman',
      'Cooper S Convertible',
      'Cooper S Countryman',
      'Cooper S Countryman All4',
      'Cooper S Coupe',
      'Cooper S Hardtop',
      'Cooper S JCW GP',
      'Cooper S Paceman',
      'Cooper S Roadster',
      'JCW Clubman',
      'JCW Convertible',
      'JCW Countryman',
      'JCW Coupe',
      'JCW Hardtop',
      'JCW Paceman',
      'JCW Roadster'
    ],
    Mitsubishi: [
      '3000 GT',
      'Cordia',
      'Diamante',
      'Eclipse',
      'Endeavor',
      'Expo',
      'Galant',
      'Lancer',
      'Mighty Max',
      'Mirage',
      'Mirage G4',
      'Mirage Station Wagon',
      'Montero',
      'Outlander',
      'RVR',
      'Raider',
      'SP',
      'SPX',
      'Space Wagon',
      'Sterling 360',
      'Sterling COE',
      'Tredia',
      'Wagon',
      'I-MiEV'
    ],
    Nissan: [
      '200SX',
      '240SX',
      '300ZX',
      '350Z',
      '370Z',
      'Altima',
      'Altra',
      'Altra-EV',
      'Armada',
      'Axxess',
      'Cube',
      'Frontier',
      'GT-R',
      'Juke',
      'Kicks',
      'Leaf',
      'Maxima',
      'Micra',
      'Murano',
      'NV',
      'NV200',
      'NV3500',
      'NX',
      'NX/Sentra',
      'Pathfinder',
      'Pickup',
      'Pulsar',
      'Quest',
      'Rogue',
      'Sentra',
      'Sentra/200SX',
      'Stanza',
      'Titan',
      'Van',
      'Versa',
      'Versa Note',
      'X-Trail',
      'Xterra'
    ],
    Porsche: [
      '718',
      '911',
      '918',
      '924',
      '928',
      '944',
      '968',
      'Boxster',
      'Carrera',
      'Cayenne',
      'Cayman',
      'Macan',
      'Panamera'
    ],
    Saab: [
      '9-2X',
      '9-3',
      '9-4x',
      '9-5',
      '9-7',
      '9-7X',
      '900',
      '9000',
      'Scania'
    ],
    Subaru: [
      'Ascent',
      'B9 Tribeca',
      'BRZ',
      'Baja',
      'Brat',
      'Crosstrek',
      'DL',
      'Forester',
      'GL',
      'GL-10',
      'GLF',
      'Impreza',
      'Justy',
      'Legacy',
      'Loyale',
      'Outback',
      'RX',
      'SVX',
      'WRX',
      'XT',
      'XT6',
      'XV CrossTrek'
    ],
    Suzuki: [
      'Biturbo',
      'Coupe',
      'Ghibli',
      'Granturismo',
      'Levante',
      'Merak',
      'Quattroporte',
      'Spyder',
      'TC'
    ],
    Tesla: ['Model 3', 'Model S', 'Model X', 'Roadster'],
    Toyota: [
      '4-Runner',
      '86',
      'Avalon',
      'Camry',
      'Camry-Hybrid',
      'Cargo Van',
      'Celica',
      'Celica Supra',
      'Corolla',
      'Corolla IM',
      'Corolla Matrix',
      'Corona',
      'Cressida',
      'Echo',
      'FCHV-Adv',
      'FJ Cruiser',
      'Highlander',
      'Land Cruiser',
      'MR2',
      'Mirai',
      'Paseo',
      'Previa',
      'Prius',
      'Rav4',
      'Scion',
      'Sequoia',
      'Sienna',
      'Solara',
      'Starlet',
      'Supra',
      'T100',
      'Tacoma',
      'Tercel',
      'Tundra',
      'Venza',
      'Yaris'
    ],
    Volkswagen: [
      'Atlas',
      'Beetle',
      'Bus',
      'CC',
      'Cabrio',
      'Cabriolet',
      'Camper',
      'Corrado',
      'Dasher',
      'Eos',
      'Euro Van',
      'Fox',
      'GTI',
      'Golf',
      'Jetta',
      'Kombi',
      'Passat',
      'Phaeton',
      'Quantum',
      'R32',
      'Rabbit',
      'Routan',
      'Tiguan',
      'Touareg',
      'Vanagon',
      'Scirocco'
    ],
    Volvo: [
      '240 Series',
      '260 Series',
      '700 Series ',
      '740 Series',
      '760 Series',
      '780 Series',
      '850 Series',
      '940 Series',
      '960 Series'
    ]
  };

  constructor() {}

  getMakes() {
    return this.makes.slice();
  }

  getModelsFromMake(make) {
    if (!make || make === null) {
      return null;
    }
    let makesFinal = null;
    try {
      makesFinal = this.makesAndModels[make];
    } catch (error) {
      console.error('Make does not exist for model');
    }
    return makesFinal;
  }
}
